KRSupdated_09122021/force-app/main/default/objects/Cart_Product__c/Cart_Product__c.object-meta.xml
<CustomObject>
    <label>Cart Product</label>
    <nameField>
        <displayFormat>CP-{0000}</displayFormat>
        <label>Cart Product ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Cart Products</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KRSupdated_09122021/force-app/main/default/objects/Contact_Address__c/Contact_Address__c.object-meta.xml
<CustomObject>
    <description>This object is used to store different contact address.</description>
    <label>Contact Address</label>
    <nameField>
        <label>Contact Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Address</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KRSupdated_09122021/force-app/main/default/objects/MyOrder__c/MyOrder__c.object-meta.xml
<CustomObject>
    <label>MyOrder</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MyOrder</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

KRSupdated_09122021/force-app/main/default/objects/MyOrder__c/fields/Contact_Address__c.field-meta.xml
<CustomField>
    <fullName>Contact_Address__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact Address</label>
    <referenceTo>Contact_Address__c</referenceTo>
    <relationshipLabel>MyOrder</relationshipLabel>
    <relationshipName>MyOrder</relationshipName>
    <type>Lookup</type>
</CustomField>

KRSupdated_09122021/force-app/main/default/objects/OrderItems__c/OrderItems__c.object-meta.xml
<CustomObject>
    <label>OrderItems</label>
    <nameField>
        <displayFormat>OI-{0000}</displayFormat>
        <label>OrderItems Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OrderItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

KRSupdated_09122021/force-app/main/default/objects/OrderItems__c/fields/MyOrder__c.field-meta.xml
<CustomField>
    <fullName>MyOrder__c</fullName>
    <label>MyOrder</label>
    <referenceTo>MyOrder__c</referenceTo>
    <relationshipLabel>OrderItems</relationshipLabel>
    <relationshipName>OrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

KRSupdated_09122021/force-app/main/default/classes/orderController_test.cls
@isTest
/*Test class on orderController*/
public class orderController_test {
/* instantiation is created to add the records of every object in the test class*/
public static testmethod void getAccount(){
test.starttest();
List< Account> newlist= orderController.getAccount();
List< Contact_Address__c> newlist1= orderController.getAddress();
List< MyOrder__c> newlist2= orderController.getOrders();
List<Cart_Product__c> newlist3= orderController.moveToOrder();
List< MyOrder__c> newlist4= orderController.getdeliverdOrder();
List< MyOrder__c> newlist5= orderController.getstatus('a0C5g000001qSyEAZs');
List< OrderItems__c> newlist6= orderController.getorderItem('a0B5g000000evBoEAI');
    
//static testMethod void test_deleteorder_UseCase1(){
    orderController controller = new orderController();
    orderController.deleteorder('01p90000006uk2w');
  
test.stopTest();
}
/* Passing parameter to deletecart method*/
@istest static void deletecart()
{

List<Cart_Product__c> c = [select Id from Cart_Product__c];
orderController.deletecart('a0B5g000000GjMCEA5');
}

}